spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lhj?serverTimezone=UTC  # 데이터베이스 URL
    username: root                       # 데이터베이스 사용자 이름
    password: 4370               # 데이터베이스 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버 클래스

jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      format_sql: true

logging.level:
  org.hibernate.SQL: debug