spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sandbox?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: yonghyun
    password: 4198
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: dydgus0831@gmail.com
    password: tvjc ctll nweu yzum
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  oauth:
    kakao:
      client-id: "0da56a0700a56821782b91c49ce03b42"
      redirect-uri: "https://ssafysandbox.vercel.app/oauth/redirect"
      token-url: https://kauth.kakao.com/oauth/token
      user-info-url: https://kapi.kakao.com/v2/user/me

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
